### ISSUE TITLE
Update seed_create along lines of wireframe

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#101]
Handles single seed and multiple seeds being added. 
What kind of validation are we doing at this point?

**Comment by lwrubel** [comment]
Am I correct in understanding that either a uid or token, but not both, is required for a seed to be valid? Working on the new seed form.

**Comment by rajatvij** [comment]
No i think both can be there too. 

For better clarity, in twitter's case: token is just the screen_name for an account whereas uid is the unique id for that account. So token may change over time, but uid will remain same. I think its same for Flickr too, where they have nsid instead of uid.

So for seed create we just need to give either token or uid or we can even give both uid and token if we want. We just need to make sure we are giving at least one of the field while creating seed

**Comment by kerchner** [comment]
That makes sense, but then you'll need to opt whether to allow the user to
enter both. If the user enters both, you'd need to validate that the uid
corresponds to the screen name, and handle accordingly if it doesn't
validate.

**Comment by kerchner** [comment]
#158 has been created with the scope of seed validation.  For #101, just allow entry of token and UID, with no validation.
