### ISSUE TITLE
Unclarities regarding seed activations

### ISSUE THREAD

**Issue by SvenLieber** [gwu-libraries/sfm-ui#1052]
I added a Twitter search collection with three seeds. The UI presents me the error message `Deactivate all seeds except 1 before harvesting can be turned on.`

In particular I am wondering what this means, can I only have one seed?
I also didn't find a way to deactivate a certain seed.

The Screenshot below shows the collection with all three seeds. In this example we used three seeds because because according to the documentation more than 10 search terms per query are not recommended.

![image](https://user-images.githubusercontent.com/3501171/105884491-5101a800-6008-11eb-967d-cd587f203a2b.png)

## How can seeds be deactivated?

I also cannot find a way to activate/deactivate seeds.
In the Screenshot below I see that `is_active` was changed from `blank` to `True`, I assume together with the creation of the seed. But where can I deactivate it again? I don't see a button. The delete button is also not clickable.

![image](https://user-images.githubusercontent.com/3501171/105884800-a2119c00-6008-11eb-951f-f7fb1b84ada7.png)

**Comment by lwrubel** [comment]
I apologize for this being confusing, we can improve the documentation. A search collection uses a set of search terms in a seed. Only one seed is used, so all of the terms need to be in one seed. If you want to run multiple sets of 10-term queries, that is best accomplished by setting up multiple search collections, each with its own single seed. 

To delete a seed, click on the query statement and then use the delete button:

<img width="897" alt="Screen Shot 2021-01-26 at 4 34 57 PM" src="https://user-images.githubusercontent.com/1619369/105908864-be0b4280-5ff4-11eb-99f5-644bed04a3c1.png">
<img width="989" alt="Screen Shot 2021-01-26 at 4 36 20 PM" src="https://user-images.githubusercontent.com/1619369/105908873-c1063300-5ff4-11eb-8e39-72258c168498.png">

Let me know if this is not addressing your question. By the way, thank you for all of your other input about your use case and sending the PR. It's great to know SFM could be useful in your work. I'm sorry our team hasn't had a chance yet to discuss the proposal and respond, but we are hoping to soon.

**Comment by SvenLieber** [comment]
Hi,

yes thanks, your answer helped, I split it now into separate collections.
The only thing I'm wondering is how to deactivate a specific seed (in contrast to just deleting it) as I see in the collection update view that all three seeds have "Active: yes". In case this functionality does not exist this would not be a problem, I was just curious.

For some reason I also cannot delete the seeds. The delete button which is dark red in your Screenshot is more light red for me and not clickable. However, I can't reproduce it. For newly created collections the delete button is fully functional. There must have gone something wrong when I created the seeds, but as I have new separate collections anyway there is no issue for me :-)

**Comment by lwrubel** [comment]
To improve the UI, work includes updating table headers that are not aligned properly, reviewing documentation for opportunities to improve seed deactivation instructions, and attempting to replicate the situation with pink button instead of red.

**Comment by dolsysmith** [comment]
Was able to replicate the behavior that Sven reported. If the collection is **deactivated**, then it is not possible to delete or undelete seeds. This is confusing, because the warning indicates that one should deactivate (delete) all seeds except one in order to turn on harvesting. If one glosses over the difference between activation and harvesting, the warning and the UI behavior (if the collection is currently deactivated) seem contradictory.

It seems that in such cases it should be possible to delete a seed before the collection has been activated. This change would probably clear up the confusion. Is there any reason not to allow seed deletion/undeletion when a collection has not been activated?

Also, I changed the text of the warning from `Deactivate all seeds except 1 before harvesting can be turned on` to `Delete all seeds except 1...` since it's not technically possible to deactivate seeds, only to delete them.
