### ISSUE TITLE
document initial messaging spec

### ISSUE THREAD

**Issue by dchud** [gwu-libraries/sfm-ui#11]
Publish to either read the docs or on repo wiki.

**Comment by justinlittman** [comment]
Drafting specification here:  https://github.com/gwu-libraries/sfm-ui/wiki/Messaging-Specification

Once it becomes stable, will move to `docs/`.

**Comment by dchud** [comment]
Work on additional details for export will come in a later milestone.

**Comment by dchud** [comment]
@rajatvij and @dchud to review draft on wiki.

**Comment by justinlittman** [comment]
Based on our discussion yesterday and in the interest of aligning with ui model, I propose the following changes:
* For harvest start message, create an options field to align with SeedSet.harvest_options.
* For harvest start message, change seeds field to align with Seed.seed_token and Seed.seed_uid.
* For harvest start message, rename auths field to credentials.
* For harvest status message, rename fields to started_date and ended_date.

**Comment by justinlittman** [comment]
Made the changes:  https://github.com/gwu-libraries/sfm-ui/wiki/Messaging-Specification/_compare/97e99656084d56a854cd902d126588db25574b09

**Comment by rajatvij** [comment]
@justinlittman According to message specification a seed may contain token and uid(which is optional). Just confirming if uid should be optional here as i thought that would be which would finally point to the seed as token may change but uid should remain same in some cases.
And  in case of Web resource harvest message, i am a little unclear on the changes in line 180-185. Is it updating the token value of a seed with the given uid between line 180-182, If so then what is meant by line 183-185?

**Comment by justinlittman** [comment]
A user might provide the token, but not know the uid.  In this case, there would only be a token, but not a uid.  If the harvester found a uid for the token, it should return in the harvest status message and so that it can be provided in future harvest request messages.

180-182 is the harvester providing the most recent token for a uid (since the token can change).
183-185 is the harvester providing a uid for a token (for the cases in which only a token was provided because the uid was not known).

**Comment by rajatvij** [comment]
@justinlittman So that means in line 180-182 user has provided uid '131866249@N02' and username 'justin.littman' which is updated to 'j.littman'?
And in line 183-185 user has provided only username 'library_of_congress' which is mapped to uid '671366249@N03'?
If so, than the document seems good to me and you can assign it to Dan for review.

**Comment by justinlittman** [comment]
Exactly.  Re-assigning to Dan.

**Comment by justinlittman** [comment]
Here's my cut at making the changes discussed with @dchud :  https://github.com/gwu-libraries/sfm-ui/wiki/Messaging-Specification/_compare/7d0e2ac009596272e51d0ba0cf686710fab618b9

**Comment by dchud** [comment]
I see several of the things we talked about in there, and this is good progress for this cycle.  I still have some quibbles with choices you've baked in (e.g. extracting urls and writing to warcs as explicit parts of a harvest vs. options or serial actions) but they are just quibbles, so let's go with your approach for now.  As you've noted in the spec itself, we will have a lot to iterate on here as we go.
