### ISSUE TITLE
How long time does it take to export  a 118G collection?

### ISSUE THREAD

**Issue by fishfree** [gwu-libraries/sfm-ui#1150]
I have a collection as below:
Data collected: 5,128 files (118.3 GB)
tweets: 161,662,649

How long will it take to export it into a single CSV file? I have executed this exporting task for 4 days. It is still running.

**Comment by fishfree** [comment]
Another day passed, it's still running.
Is there a manual way to export it? I mean in which folder, with which commands or scripts to export a collection? Many thanks!

**Comment by dolsysmith** [comment]
Sorry, @fishfree, I am just now seeing this. Did your export finish? To answer your question, you can run the Twitter exporter from the command line, though I imagine that would take an equivalent amount of time. Are you seeing any indication in the Docker logs for why the export might be taking so long? In our experience, running out of disk space will cause an exporter to hang indefinitely, so that's something to check.

**Comment by fishfree** [comment]
@dolsysmith Thank you! Sorry for replying late. I gave up last week. Still not complete.
