### ISSUE TITLE
set up static files

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#121]
specific first need is in order to add css to improve vertical button spacing as in #95 and #96

**Comment by rajatvij** [comment]
@kerchner and @justinlittman According to two scoops book. Both static files and templates needs to be at same folder where manage.py is so all apps can have a single place for all templates and static files instead of each app having their individual templates and static files. Should i follow that or i can place static folder inside ui folder which is more in sync with what we are currently having. Which option sounds better?

Option 1:
- sfm-ui/
  - sfm/
     - message_consumer/
     - sfm/
     - ui/
     - templates/
     - static/
     - manage.py

Option 2(i prefer this):
- sfm-ui/
  - sfm/
     - message_consumer/
     - sfm/
     - ui/
         - templates/
         - static/
     - manage.py

Option 3:
Or i can leave templates folder where it is but i can create static folder at the same level as manage.py

**Comment by kerchner** [comment]
sfm-ui is not likely to entail more than one app, so Option 2 should be fine.
