### ISSUE TITLE
Reconsider GET vs. POST request for creating seedsets off collections

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#132]
Currently the Add Seedset button submits to the Seedset Create page as a GET request, and puts the collection id visibly in the URL.

**Comment by rajatvij** [comment]
@kerchner I have been thinking about how to deal with this. Although i think we can use POST while creating a seedset to show seed details, but we would need to implement post on seeset list screen too as when we try to access a seedset from there, we would need to post seedset id to show seedset detail from there too. And that process itself would need addition of AJAX/jquery or maybe javascript which may make it way more complex than it needs to be.
Easier solution would be that we can either use a slugfield instead of id or encode the id in url with base64 or any other encoding. We would still be using GET in this solution, but its just that we wont be see id in URL. And i dont think this would require much change in our existing code.

Please let me know which solution sounds better and i can start working on it.

**Comment by kerchner** [comment]
cc'ing @lwrubel

**Comment by lwrubel** [comment]
@rajatvij is right that the POST has to apply to the whole hierarchy of collection > seedset > seed views, which is a pain and seeming against the grain of Django. 

I am OK with our current GET approach which makes the id plainly visible in the URL. But perhaps there is something I'm not understanding about slugfields.

**Comment by rajatvij** [comment]
Slugfield will just let us replace id in the URL with slugfield, providing us a bit of obscurity. It will be using current GET approach only the url would contian slugfield instead of ids.

**Comment by lwrubel** [comment]
I'm interested to hear what @kerchner thinks too, but I'm wondering if we really need the obscurity. Perhaps something to consider the future, and good to know about slug fields as a possible approach.

**Comment by kerchner** [comment]
We decided to stick with approach as is.
