### ISSUE TITLE
Sign up fails

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#206]
Steps to reproduce:
1. Select Sign Up.
2. Complete sign up form and submit.

Expected result:
No account is created.

Actual result:
Connection refused error.

**Comment by rajatvij** [comment]
@lwrubel I think this is because we are not using django-allauth properly. Please let me know if you have any questions on django-allauth or you need me to look into it.

**Comment by lwrubel** [comment]
The eventual goal is to use GW shib-based authn, so I think we first need to decide whether we want users to be able to create their own accounts right now. We could have a mediated account set-up step until we have GW shib-based authentication. Our users stories say "An SFM admin creates a new user account (linked to her university account) and a group account for her". 

Some options are:
- remove the link to Sign Up altogether, for now at least
- leave the link but put on that page contact info for the admin staff
- allow unmediated sign up with non-GW credentials for now

That said, are there particular issues with our used of django-allauth that look like they should be addressed right now?

**Comment by rajatvij** [comment]
Not really, actually as of now we are not using django-allauth at all. It is something that we might use in future to get credential details from various social media platforms instead of manually entering the details the way we are doing it right now.

Ideal condition would be for us to use it for all access as this supports shiboleth too and we can potentially plug in GW based authentication along with other social media platform plug in for getting their credential details. But i think that might be alot of work as It is easier to plug in social media sites in allauth than a shiboleth based custom authentication and it might also create issue with double authentication when we try to access other social media platforms when we are already logged in with GW account.

That said, i think giving contact info for admin staff seems more reasonable at the moment.

**Comment by rajatvij** [comment]
@lwrubel Sorry i just noticed that we are using django-allauth for login and logout for the user. Apologies for misinforming you above.

**Comment by kerchner** [comment]
1.  Allow self-registration (require email)
2.  Deploy within GW VPN space
3.  Note in documentation that current implementation allows anyone to sign up.  Recommend not allowing this.

Will need to resolve question of which group a newly registered user is a member of.  Consider creating a new group for each user.  Admins can then put groups of particular users into shared groups as needed.
