### ISSUE TITLE
Notifications for export completion

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#207]
Add in-ui support for notifications when export complete. Consider email also.

**Comment by rajatvij** [comment]
We can use following approach for this:

1. Use default [django messages](https://docs.djangoproject.com/en/1.8/ref/contrib/messages/) for flash user notifications and Use default [django send_mail()](https://docs.djangoproject.com/en/1.8/topics/email/) for sending mails. 
NOTE: Both django messages and send_mail() are straightforward and can be implemented without much work. This approach might be simpler to implement.

2. Use third-party apps such as [django-heythere](https://django-heythere.readthedocs.org/en/latest/index.html#indices-and-tables) for doing both together. 
NOTE: There are many apps for notification which supports from tweets to sms. The given app supports both mail and django messages and pretty straight forward. The only advantage here would be that we would need to change code similar to django messages and it is persistent.

Let me know which sounds better.

**Comment by justinlittman** [comment]
Please proceed with the first approach.

**Comment by rajatvij** [comment]
@justinlittman I am unable to send mail via google as they block sending mails from lesser secure apps and sends a sign-in prevented email response.

Error Message

> 
smtplib.SMTPAuthenticationError: (534, '5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbsh\n5.7.14 eRpxfaUIj_83NvtOhXY-5grgnKfkNR6w_71axh0sfA3rmEGgTTQzlVgLcsDkzhwGti3-MS\n5.7.14 Ra_JMi_xfR6Gy3ATwdNqQIjAbPyOyBwtKQU6SJBjWFSRSGSd3jCD42gXHvsIeCtPLncHaX\n5.7.14 INDplsS_ywcYNtdDaxoPG7HfoJgqBTpPj2QLohtKSIJ2g-PB6nVuosp2rP1tMB3ZS9UqBb\n5.7.14 nftsuwy-CzgsHK2E-ExZNYeKQ-Pbk> Please log in via your web browser and\n5.7.14 then try again.\n5.7.14  Learn more at\n5.7.14  https://support.google.com/mail/answer/78754 f91sm3319672qgf.4 - gsmtp')

The way we can bypass this is by allowing lesser secure app to use the email id from which we need to send the mail to users by Turning on following security feature https://www.google.com/settings/security/lesssecureapps. 

I am looking for a solution which doesnt need us to change our email account settings. If we can't find a solution for this(which is very probable scenario as same issue is observed when we try to send mails using python), then we might need to use a dummy account to test this out and change its security settings to allow sending mails from lesser secure apps. 

As for the messages, since django messages framework depends on requests, i have dropped it for now.

**Comment by justinlittman** [comment]
I don't know if this helps, but in the CI environment, using my
justinlittman@email.gwu.edu account was OK, but Google didn't like
justinlittman@gmail.com.

**Comment by rajatvij** [comment]
@justinlittman Just tried email.gwu.edu, gwmail.gwu.edu and got the same result. Google only lets you send mails if this [security settings](https://www.google.com/settings/security/lesssecureapps) is on for your account.

I tried yahoo and that worked. I am trying to tie the recievers email address to user's email address.

**Comment by kerchner** [comment]
Completed in #225
