### ISSUE TITLE
Process for dumping json from warcs

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#334]
For maximum flexibility, this should probably be a documented process performed from a processing container.  In particular, it should allow:
* Filtering (e.g., via jq)
* One file per WARC or merging
* Dumping only new WARCs (when one file per WARC)
* Preserving directory structure or placing in single directory
* Clear status
* In parallel

**Comment by Tanych** [comment]
When I follow the recipes to export the `warc.gz` to `json`, some tiny issues happens:
### Read only
For the command of creating a list of WARC files:
```
find_warcs.py 7c37157 | tr ' ' '\n' > source.lst
```
It's better to note that it runs on containers. The shell created by example in [Processing in container](https://github.com/gwu-libraries/sfm-ui/blob/46d535c591196b587f9d7ccd4bbebd29ddd1c582/docs/processing.rst#processing-in-container) is only allowed to read `sfm-data`.  If someone wants to create the `source.lst` on the new bash shell, they should have permission to write. 

### sfm-utils
The sfm-util needs to update to 0.4.1 or later since the wrapping of gzip, otherwise it would be pending on the screen for a long time. 

I am not sure whether it's neccessary to change the name start with `short_`  to  `source.lst` or `dst.lst` in  order to make the command run smoothly when someone tries to copy it:

**Comment by justinlittman** [comment]
I've you've pulled the latest processing container, the bash shell should be started in /sfm-processing where you should have write permissions.

Yeah, processing will be slow without the new WARC iterators.  I think that is OK for now.

Fixing short_.

**Comment by Tanych** [comment]
The PR https://github.com/gwu-libraries/sfm-ui/pull/371 can be merged. It works when someone follows the recipes to export JSON from WARCs files.
