### ISSUE TITLE
Determine what happens if tweet loaded multiple times into ELK

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#336]

**Comment by Tanych** [comment]
It might not a problem since the tweets `id` is unique. We already set the tweets `id` as the elasticsearch `document_id`. The elastic-search will not allow duplicates records. 

### Demo
Start tweets search 3 times without incremental options.
* Total tweets in sfm-ui stats: 5304
* Total tweets in Kibana: 1906

No duplicates happen in Kibana.

### Similar checks
[Eliminating Duplicate Documents in Elasticsearch](https://qbox.io/blog/minimizing-document-duplication-in-elasticsearch)

**Comment by justinlittman** [comment]
Does it replace with the latest or keep original?

**Comment by Tanych** [comment]
In real, it's hard to determine whether elasticsearch has updated the content with the same `_id` because all the content would be the same if the `tweet_id` is the same.  I am trying determine whether it can automatically update the content in the following scenario.

### Scenaria
Raw index tweets in elasticsearch 
```python
{
_index: "logstash-2016.06.19",
_type: "tweet",
_id: "744657661904453600",
_version: 1,
found: true,
_source: {
sm_type: "tweet",
id: 744657661904453600,
user_id: "342001841",
screen_name: "rebel_real",
created_at: "Sun Jun 19 22:26:36 +0000 2016",
text: "@kenklippenstein found it. it's hyperlinked as "document 8" at https://t.co/L4VD1p47ys",
user_mentions: [
"kenklippenstein"
],
hashtags: [ ],
urls: [
"http://nsarchive.gwu.edu/NSAEBB/NSAEBB462/"
],
@version: "1",
@timestamp: "2016-06-19T22:26:36.000Z",
host: "bc8dc5dde6ca"
}
}
```
When I try PUT a update to a tweets id `744657661904453600`. 

The search result would be like:
```python
{
_index: "logstash-2016.06.19",
_type: "tweet",
_id: "744657661904453600",
_version: 2,
found: true,
_source: {
sm_type: "tweet",
id: 744657661904453600,
user_id: "342001841",
screen_name: "rebel_real",
created_at: "Sun Jun 19 22:26:36 +0000 2016",
text: "@kenklippenstein UPDATED. its hyperlinked as document 8 at https://t.co/L4VD1p47ys",
user_mentions: [
"kenklippenstein"
],
hashtags: [ ],
urls: [
"http://nsarchive.gwu.edu/NSAEBB/NSAEBB462/"
],
@version: "1",
@timestamp: "2016-06-19T22:26:36.000Z",
host: "bc8dc5dde6ca"
}
}
```

The content of `text`  has been updated. Also, the elasticsearch provides [Update API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html) to do so.
