### ISSUE TITLE
Tumblr Harvester / Exporter / etc.

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#358]

**Comment by justinlittman** [comment]
Notes on code review:
1.  The tumblr harvester can be made even simpler by getting rid of Oauth altogether.  If my reading to the tumblr api is correct, then we just append the consumer key as a parameter.  For example: https://api.tumblr.com/v2/blog/justinlittman.tumblr.com/posts?api_key=Fki0Q9w9QcW95yy66RtFCni14QpM0pjuHbDWMrZ9aPXcsthVQq
2. Number of retries, delays, etc. in tumblrarc should be configurable rather than hardcoded.
3. I'd suggest removing the dependency on twarc.
4. Please document the parameters for [blog_posts()](https://github.com/gwu-libraries/sfm-tumblr-harvester/blob/master/tumblrarc.py#L101).
5. According to the API documentation, the maximum number of posts that can be retrieved at a time is 20, not 50.
6. Unclear why you're breaking [here](https://github.com/gwu-libraries/sfm-tumblr-harvester/blob/master/tumblrarc.py#L145) if not incremental.
7.  Not sure position is a reliable way to store the state for incremental harvests.  What is a post is deleted in between harvests?  It will throw off the incremental retrieval.
8.  If [post](https://github.com/gwu-libraries/sfm-tumblr-harvester/blob/master/tumblrarc.py#L170) isn't used, then get rid of it.
9. tumblrarch needs unit tests (suggest vcrpy), especially for incremental harvests.
10.  It seems like there are 2 ways of exiting the loop.  1. Hit the end of the while and 2. Return 0 posts.  If logic is correct, should only need one or the other, not both.

**Comment by justinlittman** [comment]
On TumblrHarvester:
1.  Instead of calling it user_posts, call it blog_posts (since the unit of harvest selection is a blog, not a user).
2. At https://github.com/gwu-libraries/sfm-tumblr-harvester/blob/master/tumblr_harvester.py#L43, "harvesting blog", not "harvesting user".
3.  Are you sure you want to add max_last_post and last_post at https://github.com/gwu-libraries/sfm-tumblr-harvester/blob/master/tumblr_harvester.py#L59?  I'm not following the logic.
4.  Other types of posts (e.g., link posts) can have photos, not just photo posts.
5.  What about media in audio and video posts?

**Comment by justinlittman** [comment]
On TumblrWarcIter:
1. Probably want to limit to api.tumblr.com/v2/blog/{blog-identifier}/posts, instead of just api.tumblr.com/v2 to avoid processing other records that don't contain posts.
2. [Selecting](https://github.com/gwu-libraries/sfm-tumblr-harvester/blob/master/tumblr_warc_iter.py#L26) should probably be on blog name.

**Comment by justinlittman** [comment]
Code review notes:
1. Add commandline invocation to tumblrarch.py.
2. In tumblr_harvester.py line 61 use a smaller number like 25 instead of 100.
3. In forms.py line 547 please use a different example than justinlittman.tumblr.com.
4. In models.py line 188 missing a space.

**Comment by justinlittman** [comment]
Testing notes:
1.  Does not properly handle a bad blog name (that results in a 404).  Should catch the 404 and report the bad blog name back as a warning.
2.  Links, images not extracted from this blog post:  http://justinlittman.tumblr.com/post/140636748714/downloading-un-security-council-resolutions-or

**Comment by justinlittman** [comment]
To do items:
1.  Add to sfm-docker, including processing container Dockerfiles.
2. Update all documentation and project site.

**Comment by justinlittman** [comment]
Also, credential naming issue when connecting a tumblr account.

![screen shot 2016-08-18 at 3 11 09 pm](https://cloud.githubusercontent.com/assets/588335/17787194/1d2f2162-6556-11e6-8d91-4e32d6e1bd4d.png)

**Comment by justinlittman** [comment]
@justinlittman:  Still need to look more closely at changes in view.py around line 350.

**Comment by justinlittman** [comment]
Reviewed changes in view.py mentioned in previous comment.

**Comment by Tanych** [comment]
@justinlittman 
* For the 404 error, I think it already handled the invalid URLs, it will try 10 times and raise an error of 404 warnings. 
* for images in http://justinlittman.tumblr.com/post/140636748714/downloading-un-security-council-resolutions-or, it stores the raw data on the body part. I need to analysis the html tags to extract the images and links. It looks like this:
```html
<img src=\"https://65.media.tumblr.com/e29ca96f6a4d109d3ae8a03fcea0a3d2/tumblr_inline_o3ojawjiNw1t0f420_540.png\" data-orig-width=\"666\" data-orig-height=\"514\"/>
</figure>
<p>I&rsquo;ll skip the part where I tried using wget and tried wrestling with the UN&rsquo;s inscrutable </p>
```
* The name issue I didn't reoccur. I am not sure what's wrong with the connecting Tumblr account.

**Comment by justinlittman** [comment]
* For the 404 error, the harvester should report back a bad blog name by a warning message in the harvest result.  See how the Twitter harvester handles this in https://github.com/gwu-libraries/sfm-twitter-harvester/tree/sfm_346-timeline_problems.
* Yes, I think we will need to do some (basic) link extraction.  Consider https://www.crummy.com/software/BeautifulSoup/

**Comment by Tanych** [comment]
Got it. Thanks!

**Comment by Tanych** [comment]
@justinlittman 
All pull requests related:
* [sfm-docker](https://github.com/gwu-libraries/sfm-docker/pull/5) adding sfm-tumblr-harvester
* [sfm-tumblr-harvester](https://github.com/gwu-libraries/sfm-tumblr-harvester/pull/3) adding 404 and extracting links from html based on [beautifulsoup](https://www.crummy.com/software/BeautifulSoup/)
* [sfm-ui](https://github.com/gwu-libraries/sfm-ui/pull/373) fix instructions 

whether there are any other documents need to be added?
