### ISSUE TITLE
Add ability to bulk-add seeds by UIDs

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#404]
Along with this, we should validate:
- when adding by Twitter screennames, prevent the user from adding screennames that are entirely numeric (this currently throws an exception - see #355 
- when adding by Twitter UIDs, prevent the user from adding screennames that are _**not**_ entirely numeric (should double-check that entirely numeric screennames are disallowed)

Also verify how this works for other platforms besides Twitter (for example, Flickr usernames vs. nsid-s).

There are different ways we can design the UI, but I would suggest a single bulk list entry field, plus a radio button (prominent, perhaps above the list-entry field) where the user selects screennames vs. UIDs.  Suggest defaulting the radio button value to "None" so that the user must consciously select the value.  The value would be required.

**Comment by Tanych** [comment]
I am not sure whether adding radio button can avoid the invalid input since the users can also input  entirely numeric when they choose `screennames`. What I think about this issue is that users added the bulk seeds (token or uids) in a single bulk list. We separate the uids with some patterns like twitter uids are entirely numbers and Flickr users seems like `1233@N001` .  We'd better discuss a little more in this issue.

**Comment by kerchner** [comment]
Note that the scope of this issue is limited to Twitter.  Analogous enhancements to other platforms' seed management will be in separate, future tickets.
