### ISSUE TITLE
Shibboleth integration

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#450]

**Comment by lwrubel** [comment]
Per discussion at STG meeting, consider ADFS (Active Directory Federation Services). Talk to @ihardy for details.

Campus authentication integration (whether shibboleth or ADFS) allows GW community (and other organizations' communities, potentially) to log in with their regular GW NetID instead of setting up a username and password for just this system.

**Comment by justinlittman** [comment]
No current need.
