### ISSUE TITLE
Find alternative to using gmail for sending mail

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#452]
It requires putting my password all over the place.

**Comment by justinlittman** [comment]
See what webrecorder does: https://github.com/webrecorder/webrecorder#mail

**Comment by justinlittman** [comment]
Also, should talk to @kilahimm

**Comment by Tanych** [comment]
## Trivial work
I added a mail server of `postfix` as [webrecorder docker](https://github.com/webrecorder/webrecorder/blob/master/docker-compose.yml#L118) does. However, it can only  send email in localhost and when it sends emails out to Gmail or Hotmail, it occurs an error `error: [Errno 111] Connection refused`, when I dig into this error, it has some wrong with the local mail server `postfix`. It will pop out an error with `554 5.7.1 relay access denied `.  I also tried to run the webrecorder instance locally to better understand how the mail server works, but it got lots of problem with the files or unexcepted fails. 

## Possibility
I tried to find some solution for this `554` error, some of them need to add [DNS MX Record](https://en.wikipedia.org/wiki/MX_record) on your domain since the `postfix` acts as [MTA]  (https://en.wikipedia.org/wiki/Message_transfer_agent) when sending emails. It means  a fully qualified domain name (say mail.sfm.com) is set up on the instance server. Some used the [AWS SES](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/postfix.html). They all cost some money to do that. 

## Next
Verify whether can get a free solution to get it works. 

## Reference
http://cheng.logdown.com/posts/2015/06/08/django-send-email-using-postfix
http://stackoverflow.com/questions/26333009/django-postfix

**Comment by justinlittman** [comment]
Make sure to consult @kilahimm.

**Comment by kerchner** [comment]
Or, just use sfm@gwu.edu (even on test servers etc.)

**Comment by Tanych** [comment]
@justinlittman I have fixed some error for the postfix, if we using the localhost SMTP, do it as the [webrecorder](https://github.com/webrecorder/webrecorder), the localhost can't identify the mail domain, so when someone receives the email, it might in the spam or trash.
![localtesting](https://cloud.githubusercontent.com/assets/3956411/19524378/821c9a44-95eb-11e6-9f17-7244ec271113.png)

**Comment by Tanych** [comment]
Another better docker is [tomav/docker-mailserver](https://github.com/tomav/docker-mailserver), 
* Supporting TLS
* encrypt password
* keeping updates
* well docs
* security

The account info like this:
```bash
test@localhost|{SHA512-CRYPT}$6$Hy4kYpyWpH0TVubh$QVbRgSyMUgqrBioLCdWY9JLYjJGkkvFI3fKC2DDpKGPlwxG7JSKg10vzhEixPHUepa9UgLq85yUNg53dOF/Zm/

```

**Comment by Tanych** [comment]
After the discussion, it's better to set up a new account like `sfm-noreply@gwu.edu` instead of the personal email credentials. Also, setting up the own email server might bring some new problems and the local email server docker solution also has some authentication problem.

**Comment by justinlittman** [comment]
Final decision was to create new email account for use by GW users:  sfm_no_reply@email.gwu.edu.  See me for password.
