### ISSUE TITLE
create sfm-twitter-harverster

### ISSUE THREAD

**Issue by dchud** [gwu-libraries/sfm-ui#46]
To support basic functions, starting with user_timeline.  Probably will require a new repo and docker integration.

Please create additional tickets as required.

**Comment by justinlittman** [comment]
My plan is to wrap twarc using a warcprox approach.  User timelines, search, and streams will be supported.

This will require:
* Adding user timelines to twarc.
* Experimenting with whether capturing streams will work with warcprox.

**Comment by justinlittman** [comment]
@edsu:  Bringing your attention to this ticket.

**Comment by edsu** [comment]
I'm glad to hear you are going to give warcprox a try. I've been meaning to try it out as well, and it would be nice to follow in your footsteps. Just out of curiosity what is pushing you away from using tweepy? it seems to have quite a bit of other potentially useful stuff in it that is missing from twarc?

**Comment by justinlittman** [comment]
From my perspective it's simpler and battle-tested for the specific use case of archiving tweets.

Let me flip the question:  Why did you write twarc when tweepy already existed?

**Comment by edsu** [comment]
Well played :-) 

I created twarc partly because I didn't fully understand tweepy at the time, and what I wanted to do was fairly simplistic: walk back in search results until no more could be fetched. I think tweepy's notion of cursors is more developed than when I first worked on twarc. Although, I haven't actually checked to see if tweepy's cursors work with search results, but they must right?

One other factor is that I wanted to have access to the exact JSON that Twitter sent, and wasn't sure if tweepy was playing around with it at all. So I opted to create my own utility.

**Comment by justinlittman** [comment]
https://github.com/gwu-libraries/warcprox is a modification of warcprox that supports streaming by implementing WARC record segmentation.

sf_warc_lister.py in https://github.com/justinlittman/social-feed-tools proves that these WARCs can be read and the tweets extracted.

**Comment by edsu** [comment]
seems like a great way to start ; I remember @ikreymer [saying](https://github.com/gwu-libraries/sfm-ui/issues/38#issuecomment-152559694) he had implemented warc support into requesets, which would be another potential option. The nice thing about the new architecture you've come up with sfm-ui is that different approaches could live side by side, and be invoked with different messages?

**Comment by justinlittman** [comment]
That's correct.  So while the twitter harvester will use the warc-prox technique, the existing flickr harvester uses the hacking httplib technique.  And I'm thinking of using wpull as a general purpose web harvester.  All can happily co-exist (isolated from and ignorant of the existence of the others).
