### ISSUE TITLE
HTML Export of Weibo collections doesn't render Chinese characters correctly

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#474]
Steps to reproduce:
- Export HTML from a Weibo collection.  Open the HTML in a browser.

**Comment by Tanych** [comment]
The reason for this issue is that `petl` only export the table data to HTML, the raw data in HTML like:
```html
<table class='petl'>
<thead>
<tr>
...
</tr>
</thead>
<tbody>
```
No `head` or `body`, `html` such tags, if we manual add `<head><meta charset='utf-8'></head>` in the export HTML files, it can display normally. However, we need find a way automatically to do this.

**Comment by kerchner** [comment]
Also add tags to make the output (for all platforms) valid HTML, with html enclosing tags, head, body, etc.
