### ISSUE TITLE
Consider Flickr lookupUser

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#511]
As reported @dchud:
Wanted to build a collection of all the flickr commons photos.  Started one.  Went to add seeds.

Downloaded the institution list: https://www.flickr.com/commons/institutions/

Mucked with HTML to extract account names from URLS.  e.g.:

valokuvataiteenmuseo
vcucommons
vestfoldmuseene
wwplarchives
ylearkisto
95520404@N07
99115493@N08

Bulk add seeds, type user name:  all the names.
Bulk add seeds, type NSID: all the ids.

Those were two steps.

Most of these did not work; some did, including all the NSIDs bulk added and a handful of the user ids.  The harvester brought back many errors like "NSID not found for user aahs_archives".

Poked at flickr API.  Found https://www.flickr.com/services/api/flickr.urls.lookupUser.htm and compared with https://www.flickr.com/services/api/explore/flickr.people.findByUsername.  lookupUser takes a full URL and extracts the user info, and that worked to extract all the NSIDs.

Now I'm going in and updating seeds to add NSIDs where they're missing.

I suppose SFM might stop at findByUsername now but might could fall back to try lookupUser as a last resort?  I can't tell how common a problem this might be, though.

**Comment by yonahbg** [comment]
I ran into this same problem while adding Flickr seeds. What I found is that there are up to four different identifiers for each handle:

- NSID: unique serial identifier in the format XXXXXXXX@NXX
- "Real" name: This is what may be supplied as first name/last name, and is then the largest text on the screen.
- url: unique and permanent alphanumeric identifier that is used at the end of the url
- Username (sometimes referred to as screen name in documentation): Unique alphanumeric identifier. Finding this can be a little challenging through the Flickr UI; it's usually located in small letters underneath the large profile title.

While some of these can be identical, they often are not. You can see in the attached photo that Smithsonian Libraries, for example, has four different identifiers:
url: smithsonianlibraries
Username: Smithsonian Libraries
"Real" Name: Smithsonian Institution Libraries
NSID: 7576993@N07 (I had to look this one up)

Either the NSID or the Username can be entered in SFM, and not (at least not yet?) the url. The Real name wouldn't work, since it's not unique. 
For Username entry, it has to be the Username and not the url. See this photo for where the Username can be found. I'd be curious to know whether there is an easier/more consistent way to look it up, since some profiles don't have the username in that location.

![smithsonian page capture with username circled](https://cloud.githubusercontent.com/assets/23175249/20014060/d2467ab0-a28b-11e6-90c9-0ea6b64774b9.JPG)

**Comment by yonahbg** [comment]
For now, until we integrate url lookup and find a more long term solution, there's a simple online tool that can be linked to:

[idgettr.com](url)

It works simply by putting in the url for the account and returning the NSID, which can be inserted into the SFM UI

**Comment by justinlittman** [comment]
Flickr harvester not receiving significant use.
