### ISSUE TITLE
Harvest completed dates are off

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#580]
![screen shot 2016-12-07 at 7 23 48 am](https://cloud.githubusercontent.com/assets/588335/20967593/463d5b38-bc4e-11e6-8d2a-bbf2da5f42f3.png)

Steps to reproduce:
1.  Perform a quick harvest.
2. Observe the started and completed times.

Expected results:
Started and completed times should be close.

Actual results:
Started and completed times are offset by 5 hours.

**Comment by Tanych** [comment]
@justinlittman 
For this issue, it might be the `iso8601.parse_date` in https://github.com/gwu-libraries/sfm-ui/blob/master/sfm/message_consumer/sfm_ui_consumer.py#L60, and other similar code. 
It will default add the `tzinfo=<iso8601.Utc>` to the datetime when dealing the time `2016-12-13T12:32:34.538767`. Actually,  the timezone in containers are `ETS`. So it would diff 5 hours.

**Comment by Tanych** [comment]
@justinlittman 
The timezone issue might be involve `harvester` and `sfm-ui`. There are four date values.
`date_requested`, `date_started`,`date_ended`,`date_updated`. Also, three timezone related `UTC`, `EST`, `America/New_York`.

### SFM-UI timezone.now()
source of now()
```python
def now():
    """
    Returns an aware or naive datetime.datetime, depending on settings.USE_TZ.
    """
    if settings.USE_TZ:
        # timeit shows that datetime.now(tz=utc) is 24% slower
        return datetime.utcnow().replace(tzinfo=utc)
    else:
        return datetime.now()
```
SFM-UI code:
```python
date_requested = timezone.now()
```
Since we already set `USE_TZ=True`, the `timezone.now()` will return time based on `UTC`. The database save the timeinfo with timezone `UTC`.

### Haverster datetime.now()
```python
 self.result.ended = datetime.datetime.now()
```
The above code will get the time based on local machine timezone. The `tzinfo` is empty. Mine is `EST`. 
When the sfm-ui receive the `date_ended`, for example: `2016-12-13T12:32:34.538767`. It has no timezone info. The `iso8601.parse_date` try to analysis the time, it would default add `UTC` to the `tzinfo`. The database save the time with timezone `UTC`. However, it's not correct because `2016-12-13T12:32:34.538767` in `EST` saved into database as `2016-12-13T12:32:34.538767` with tzinfo =`UTC` .

When the `SFM-UI` try to display into the setting timezone, it would totally different.
