### ISSUE TITLE
twarc enhancements

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#61]
In support of #46.

Enhance twarc with the following:
* sample stream (similar to filter stream)
* user timeline (similar to search)
* lookup users

Please complete each of these enhancements in a separate feature branch in a fork of twarc.  Once these enhancements have passed our code review/testing they will be submitted to @edsu as pull requests.

**Comment by kerchner** [comment]
What is the scope of "look up users"?

**Comment by justinlittman** [comment]
As in current SFM, there is the need to get user_ids given screen_names.  This means exercising https://dev.twitter.com/rest/reference/get/users/lookup.

**Comment by edsu** [comment]
I'm not sure if it's of interest but I thought I should let you know that I am planning to add the ability to fetch by location and user id(s) from the streaming api. See https://github.com/edsu/twarc/issues/83

**Comment by justinlittman** [comment]
I've done some testing and code review:
1.  You're a few commits behind.  Make sure to pull those in.
2.  There is an errant print statement in twarc.py (line 473).
3.  For user timeline:  For clarity, I would recommend `statuses = resp.json()` and then `if len(statuses)` and `for status in statuses:`.
4.  Similar change in lookup user, except use `user` instead of `statuses`. 
5.  User timeline doesn't do anything to support paging (e.g., by changing max_id parameter).  Without this it just loops over the first page.
6.  User lookup doesn't split into requests of 100 users.  Also, it doesn't have a way for breaking from True loop.

Let me know if you have any questions.

**Comment by rajatvij** [comment]
@justinlittman Can you elaborate a bit more on this not splitting into requests of 100 users. I tried to give multiple users and it worked for me. And do we need entities in user lookups?

**Comment by justinlittman** [comment]
What happens if someone provides 101 users?  (Answer: should be split into a request of 100 users and 1 user.)

I think it's OK to ignore the include entities parameter.

**Comment by rajatvij** [comment]
@justinlittman I pushed few changes, although i was able to split the requests in user lookup, but i couldn't figure any cleaner way to do it. Can you please check and let me know if any other modification is required.

**Comment by justinlittman** [comment]
OK.  Some more code review comments.

1.  To be pythonic, I'd suggest that user_lookup take either a single screen name or an iterable of screen names (and figure out itself if an iterable or single screen name).
1.  This might be a cleaner way to splitting into chunks:
```
>>> x = [0, 1, 2, 3, 4, 5]
>>> while x:
...     y = x[0:2]
...     print y
...     x = x[2:]
... 
[0, 1]
[2, 3]
[4, 5]
```
1.  In user_lookup, while the `while True` with a `break`?  It seems like that should exit after only one run in which case it is not necessary.
1.  I would call it "sample" instead of "samplestream" to be consistent with "filter".

**Comment by rajatvij** [comment]
@justinlittman Do you mean that we should give a list as input in our parser? 

I am trying to do that by converting the input to list by using nargs='+' while adding the argument (so that we may give multiple screen names separated by 'space') and then calling the function in following way:
```
elif args.users:
¦   print(args.users)
¦   if len(args.users)==1:      # I personally don't feel that there is any need for
¦   ¦   print(args.users[0])    # this as this can be covered in next while condition.
¦   ¦   tweets = t.user_lookup(args.users[0])
¦   else:
¦   ¦   while args.users:
¦   ¦   ¦   users = args.users[0:100]
¦   ¦   ¦   screen_names = ",".join(users)
¦   ¦   ¦   print(users)
¦   ¦   ¦   tweets = t.user_lookup(screen_names)
¦   ¦   ¦   args.users = args.users[100:]
```
This way we don't need to manipulate screen names in user_lookup function.

But this is calling the user_lookup function for last list of 100 or less elements. I must be missing something here which i am unable to identify for now. Please let me know if u know the reason. Let me know if you want me to share full code.

And if i don't put a break in while loop then it never exits the loop, maybe i shouldn't have used while true there but every other function is written in that way so i followed suit.

**Comment by rajatvij** [comment]
@justinlittman I got what is wrong with the above code. i didn't see that i was just overwriting the value of tweets in while loop. I will correct and push the changes.

**Comment by kerchner** [comment]
Removing from 0.4.  Work will resume when @rajatvij returns.

**Comment by justinlittman** [comment]
Code review:
1. For user lookup, don't change the passed list of screen names -- make a copy and change the copy.
2. At line 134, space in "-- timeline".

Defect:
1. Fetch a user timeline for justin_littman.
2. Fetch a user timeline for xxxxfoo.

Expected result:
User timeline listed for justin_littman.  No results for xxxxfoo.

Actual result:
User timeline listed for justin_littman and then repeated again.

**Comment by rajatvij** [comment]
@justinlittman It seems when we provide an invalid user_id or screen_name, twitter API returns 404 Error and it gives 401 Error for private user_id or screen_names. That only happens in case all parameter's provided are invalid or private. So all invalid and private user_id's or screen_names are being ignored and API is giving result only for valid public users for both timeline and user lookup. I can send individual request for each user instead of bulk request, but that beats the purpose of bulk request to twitter and am not sure if that would be efficient.

**Comment by rajatvij** [comment]
@justinlittman Handled 401 and 404 Error response from twitter API and updated README.md for the same. Please check and let me know if i should make any more changes to the branch. Apologies for the delay.

**Comment by justinlittman** [comment]
@rajatvij Did you push your commits?

**Comment by rajatvij** [comment]
@justinlittman yes

**Comment by justinlittman** [comment]
There's no break in timeline(), so `python twarc.py --timeline justin_littman` never stops.

**Comment by rajatvij** [comment]
@justinlittman Included break condition in timeline. Although this might need a bit of code cleanup and formatting.

**Comment by justinlittman** [comment]
I was thinking something more similar to https://github.com/gwu-libraries/twarc/blob/af9d0145e776d1edc9e97df8d5fdca31e56b66be/twarc.py#L308

**Comment by justinlittman** [comment]
* Get rid of print statement here https://github.com/gwu-libraries/twarc/blob/sfm_t61-twarc-enhancements/twarc.py#L358
* When performing a user timeline, if you enter a screen_name (e.g., gelmanlibrary) instead of a user_id (e.g., 9710852), you get your own user timeline.  I would suggest that you detect if a screen_name or user_id (all digits), and pass as appropriate parameter.

**Comment by rajatvij** [comment]
I am only passing user id for timeline as screen_name can be changed overtime. Did you really get your own user timeline when you passed a screen_name? I tried and didn't get any result. 
Please let me know if we should use both screen_name and user_id for timeline.

**Comment by rajatvij** [comment]
@justinlittman This works, but for timeline when i included support for screen_names, i am getting a 404 from twitter API after we have fetched all timeline. It is because the last request we have sent is an invalid request(due to changed max_id maybe?). I am not sure why the break condition with max_id didn't work in this case as when we use only screen_name or user_id, that break condition works. 

And we would need to regressively test this as i have ignored [https://github.com/edsu/twarc/issues/75](https://github.com/edsu/twarc/issues/75) Issue as that has not been experience after August 2015 much. 

I have updated readme and we might need to remove some of my comments, although i still think we can deal with timeline function in a better way.

**Comment by justinlittman** [comment]
@rajatvij I've made some changes to separate screen names and user ids: https://github.com/gwu-libraries/twarc/commit/34f15b28dc93a0b198b0dfc24d6ef231d9e6463b

I know I had asked you to have the code try to be smart about it, but came to the conclusion that it was just more confusing.

Can you please fix the README to reflect these changes, make sure you have the latest from Ed's repo, squash the commits, and send Ed a pull request?  If you have questions on any of the git magic, @kerchner can help you.

**Comment by kerchner** [comment]
@rajatvij Also add tests, may need a new branch/PR on our fork since https://github.com/gwu-libraries/twarc/pull/2 has already been merged.

**Comment by kerchner** [comment]
For the sake of having the comments all in one place:  Moving the comments from https://github.com/gwu-libraries/twarc/pull/3 on to here:

#### `test_timeline_user_id`:

I believe you want to assert two things:
   - That you get back tweets at all.   If `t.timeline(user_id=user_id)` is not None and you have tweets at all, then you should be able to say unconditionally that `found = True`.   The `if` clause seems to be unnecessary.   Furthermore, https://github.com/gwu-libraries/twarc/blob/sfm_t61-twarc-enhancements_tests/test_twarc.py#L166 will break as soon as `@guardian` modifies their Twitter screen name.  This test is intended to verify that it's getting tweets from the `user_id` passed as the parameter, so it makes sense to verify that the `id_str` (not the screen name) matches -- and that's taken care of by the `assert` on the line above.
   - That the tweets are from this `user_id`.  This is the `assert` statement you currently have.  

Is there a reason you're checking up to 200 tweets, rather than just the first one?  (See `test_follow` which appears to just check the first one)

---

#### `test_timeline`:

In line with the note above, this test might be too sensitive to changes in `@guardian`'s screen name.   A compromise might be to let it be case-insensitive.

----

#### `test_user_lookup`:

- Consider renaming your iterator, since `user_lookup` returns user objects, not tweets.
- I think it is fairly safe to assume that these user_ids will be around for a while (may want to note in a comment that this test may need updating in the event that one of those twitter accounts is closed).
- As currently written, I believe it's verifying that for each returned user, its user_id ***or*** its screen_name appears in one of the lists.  I think what you actually want to test here is that:
    - Each element of `user_ids` passed in is in the returned set of users, AND that
    - Each user returned is in the list of `user_ids` passed in (i.e. that it doesn't return extraneous users)
so you should consider rewriting the test accordingly, perhaps as two loops.
- Given the purpose of this test, I don't see why this one needs to involve screen names.


-----

#### `test_screen_names`:

- Consider renaming your iterator, since `user_lookup` returns user objects, not tweets.
- This test risks being fragile; we have seen screen names change even with major news organizations.  You might consider softening it a bit by doing case-insensitive compares; some of the screen name changes tend to be capitalization changes.  That will not eliminate the fragility but will reduce it.
- See the third and fourth bullets under the previous method re: restructuring the test itself, and consider whether this test needs user_ids to be involved at all.

----

#### Overall:
- Needs several PEP8 corrections.  I realize that the version in twarc/master has a few PEP8 issues, but I would recommend staying focused on the methods you're adding.
- Naming of methods:  Essentially here you're testing two methods:  `timeline()` and `user_lookup` and for each method you're testing it twice:  once using user_id(s) and once using screen name(s).  Consider more consistent naming of the test methods, perhaps:
    - `test_timeline_by_screen_name`
    - `test_timeline_by_user_id`
    - `test_user_lookup_by_screen_names`
    - `test_user_lookup_by_user_ids`

**Comment by justinlittman** [comment]
https://github.com/gwu-libraries/sfm-twitter-harvester/pull/6 is for adding the user timeline and sample stream support into the twitter harvester.

Note that this is pointing to our clone until our PR is completed and accepted.

**Comment by kerchner** [comment]
Resolved in https://github.com/gwu-libraries/sfm-twitter-harvester/pull/6 .   Follow-on work to submit PR to twarc will be in #199 .
