### ISSUE TITLE
Option to hide web harvests in harvests list 

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#738]
Add an option to filter harvest list to type, filter status at a minimum.

Use something like GitHub's limit options.

**Comment by adityadharne** [comment]
PR: https://github.com/gwu-libraries/sfm-ui/pull/766

**Comment by justinlittman** [comment]
This doesn't work quite right.

First and most importantly, it only limits against the harvests that are listed in the table, not the list of all harvests.  If I select, "Completed with errors" and none of the last 5 harvests completed with errors then nothing will be displayed. However, I may have harvests that completed with errors -- they're just not in the last 5.

Second, search doesn't make sense for limiting by harvest type. For any give collection, there will only be 2 harvest types: the collection's type and web harvest.

Third, once you get to the rest of the harvests (click View all XX harvests), there is no ability to limit.

Because the first is a defect, I'm removing from this release.

**Comment by lwrubel** [comment]
This will be simpler to implement in the harvests ListView. Set up a filter there (same dropdown as status?). Change link at bottom of Harvests table to "View all n harvests or filter further".

**Comment by justinlittman** [comment]
At this point, we're not doing many web harvests so I'm going to remove this ticket from milestone.

**Comment by justinlittman** [comment]
Closing since we're not doing many web harvests.
