### ISSUE TITLE
Consider upgrade to Django 1.9

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#74]

**Comment by justinlittman** [comment]
Might need to upgrade django-finalware to https://github.com/un33k/django-finalware/releases/tag/0.1.1.

Note that django-finalware is specified in the dockerfiles, not requirements.txt.

**Comment by dchud** [comment]
Just came out!  No rush on this.  Note that the 1.8 line is an LTS version: https://www.djangoproject.com/download/

**Comment by kerchner** [comment]
@dchud that was the intention of the "Consider" qualifier.

**Comment by rajatvij** [comment]
## Potential concerns in upgrading to django 1.9

### Packages : 

1. **django-braces** : This only supports django 1.8, but django 1.9 itself has adopted some of the functionality related to Mixins from django braces, so this might not be required. TODO: Need to check if django 1.9 can support our project.
As of now i dont see any issues related to django-braces while running sfm-ui with django 1.9

2. **django-crispy-forms** : This partially supports django 1.9. Their own tests pass 96.37% in django 1.9. While running tests i can see some RemovedInDjango110Warnings. But nothing concrete that breaks sfm-ui.

3. **django-jsonfield**: This also gives RemovedInDjango110Warning. We might not need this anymore as django 1.9 now ships with full support for Postgres' indexable JSONB datatype, as JSONField. https://docs.djangoproject.com/en/1.9/ref/contrib/postgres/fields/#django.contrib.postgres.fields.JSONField

4. **psycopg2** : Don't need this anymore as according to release notes django 1.9 extends support for postgres now and we need to change the backend name to django.db.backends.postgresql

5. **python-openid** - Not sure how we are using this? So couldn't really check this out. 

6. **SQLAlchemy** - Need to check this out although this shouldn't create a problem as this is supported by python 2.7

7. **warc** - TODO: Check required.

### Other Issues: 

1. **urls.py** : We use django.conf.urls.patterns(), which gives RemovedInDjango110Warning. So need to restructure the urls as per django release notes

2. Need to use _apps.py_ instead of [default_app_config](https://github.com/gwu-libraries/sfm-ui/blob/master/sfm/ui/__init__.py)

### Potential Modifications:

1. [**on_commit()**](https://docs.djangoproject.com/es/1.9/topics/db/transactions/#django.db.transaction.on_commit) to create queued tasks.

2. **Forms**: Has additional meta options of field_class and field_order for Modelforms, which can be leveraged to clean forms.py

3. **Models**: We can use timezone now.

4. **Urls** : Regex are allowed now, which can be leveraged for credentials create and details forms.

### Removed functionality, that we might need to look out for.

1. Postgres 9.0 is not supported anymore

2. syncdb() is removed

3. django.utils.unittest is removed.

4. django.utils.tzinfo is removed.

**Comment by kerchner** [comment]
Complete - thanks for the research, @rajatvij
