### ISSUE TITLE
Rethink Turn on / off buttons

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#752]
Harvesters using REST APIs may not need to use a Turn On / Off button workflow in the UI. We've observed this being a problem for other users and ourselves. Consider other options to implement, such as a Save button. 

@justinlittman to start and then work with @adityadharne on UI implementation.

**Comment by justinlittman** [comment]
The reasoning for the existing functionality is coming back to me:  Even for non-streaming collections, updating a collection is a multi-step process. For example, a user may change some of the settings, add some new seeds and remove some others. Turning the collection on/off prevents a harvest from being triggered while the user is in the middle of making changes.

If we're willing to ignore this risk, then there is no need to turn a non-streaming collection off for editing. (However, this would make the initial set-up of the collection a bit more confusing, as it would require a step to turn on the collection.)

An alternative is to make turning on edit mode a one step process (turn off and edit with a single click) instead of a two step process (turn off then edit).

**Comment by justinlittman** [comment]
Here's how it works as implemented:
* For streaming collections: Can only add or edit seeds if collection is active and turned off and have permissions.
* For other collections: Can only add or edit seeds if collection is active and have permissions.
