### ISSUE TITLE
Create Elastic Stack (formerly ELK) using Elastic's docker images

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#755]
The current implementation, being used for Program on Extremism data, is unsustainable as it keeps running into errors from which recovery by restarting is not possible.

@justinlittman has reviewed the current issues with the ELK stack and concluded that the best way forward is to move off the docker image we're currently using, which among other issues uses out-of-date versions of the ELK components.  Instead, we should use the current, Elastic-supported images.

See https://github.com/elastic/stack-docker and

https://www.elastic.co/guide/en/kibana/current/docker.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
https://www.elastic.co/guide/en/logstash/current/docker.html

**Comment by justinlittman** [comment]
Another problem with existing ELK is that it is using a lot of local storage (instead of being on the linked volume):
![image](https://cloud.githubusercontent.com/assets/588335/24292876/8cef9c6a-1065-11e7-89f2-a9b0004cd0c4.png)

**Comment by Tanych** [comment]
@justinlittman @kerchner 
There are two version official elasticsearch. elasticsearch:<version> VS elasticsearch:alpine
* elasticsearch:<version>
This is the defacto image. If you are unsure about what your needs are, you probably want to use this one. It is designed to be used both as a throw away container (mount your source code and start the container to start your app), as well as the base to build other images off of.

* elasticsearch:alpine
This image is based on the popular Alpine Linux project, available in the alpine official image. Alpine Linux is much smaller than most distribution base images (~5MB), and thus leads to much slimmer images in general.

For our purpose, if we take the one ` elasticsearch:alpine` which linked on the issue description, all the build bash need to rewrite since the alpine Linux has lots of different with the Ubuntu. We have no root access to the elasticsearch:alpine image. All the work need to be done on the docker file.

Which one would you prefer? the light one or more similar with current?

Another thing need to take consideration, the official said:
```
This image will receive no further updates after 2017-06-20 (June 20, 2017). Please adjust your usage accordingly.
```

**Comment by justinlittman** [comment]
elasticsearch (non-alpine) makes sense to me. Which images does it say is being deprecated? Or both?

**Comment by Tanych** [comment]
I am not sure, you can see the detail here.
https://hub.docker.com/_/elasticsearch/

**Comment by kerchner** [comment]
I would think we want supported versions:

- docker.elastic.co/elasticsearch/elasticsearch:5.3.0   -  from looking at https://github.com/elastic/elasticsearch-docker/blob/master/build/elasticsearch/Dockerfile it appears this is in fact based on Alpine.
- docker.elastic.co/kibana/kibana:5.3.0
- docker.elastic.co/logstash/logstash:5.3.0

**Comment by justinlittman** [comment]
Right, so the new, official images aren't in Docker hub. They're in docker.elastic.co.

**Comment by Tanych** [comment]
the new one is based on alpine linux, we need to rewrite some of the bash code.
Also some the environment options is not supported!

**Comment by Tanych** [comment]
@kerchner @justinlittman 
After keep following the updates of the official image, I think they might want to switch the elastic search base image from `alpine` to `centos`, since they already have the branch:

https://github.com/elastic/elasticsearch-docker/tree/switch-to-centosbase

**Comment by Tanych** [comment]
## SFM_ELK 5.x
The new sfm_elk based on official docker image [elasticsearch 5.3.0](https://github.com/elastic/elasticsearch-docker), [kibana 5.3.0](https://github.com/elastic/kibana-docker), [logstash 5.3.0](https://github.com/elastic/kibana-docker). They are three separate containers to feed in the JSON records to the elasticsearch. The simple structure like this:
![sfm_elk](https://cloud.githubusercontent.com/assets/3956411/25052670/f7725fd4-2120-11e7-8aaa-cbe57fd1e09e.png)
To make all the things more similar as the all-in-one containers, I just keep the old logical of the sfm-elk. However, there are lots of changes in order to compatible the 5.X official ELK.

## Changes
### Install
#### 1. Docker version
As the [elasticsearch Github](https://github.com/elastic/elasticsearch-docker) says: The images have been tested on Docker 1.12. It's better to update the host docker to 1.12. I have tried some version then this, it has some problem.
#### 2. Host setting
The `vm_max_map_count kernel` setting needs to be set to at least `262144` for production use. Depending on your platform. For details: click [here](https://www.elastic.co/guide/en/elasticsearch/reference/5.x/docker.html).
#### 3. Production mode vs Development mode
As the [official doc](https://www.elastic.co/guide/en/elasticsearch/reference/5.x/docker.html#_notes_for_production_use_and_defaults) suggestions,  we need to pay attention to some settings on production mode.

### Functions
The `string` field is unsupported for indexes created in 5.x in favor of the `text` and `keyword` fields. 
All the `string` field need to update either `text` or `keyword`. For the virtualization,  It's a little problem to do aggregations of top-10 hashtags with case insensitive. I have tries the official solutions, but the `keyword` isn't aggregatable when doing the dynamic mapping. 
Here some resource of  the updating:
* https://www.elastic.co/guide/en/elasticsearch/reference/current/text.html
* https://www.elastic.co/blog/strings-are-dead-long-live-strings

## New Features
### X-Pack
X-Pack is an Elastic Stack extension that bundles security, alerting, monitoring, reporting, and graph capabilities into one easy-to-install package. The most useful three are [security](https://www.elastic.co/guide/en/x-pack/current/security-getting-started.html), [graph](https://www.elastic.co/guide/en/x-pack/current/graph-getting-started.html) and [monitoring](https://www.elastic.co/guide/en/x-pack/current/monitoring-getting-started.html). However, it's not free. They are different levels' [license](https://www.elastic.co/subscriptions). The free license only provides monitoring.
For the initial version of the SFM_ELK 5.x, I will disable all the features of the X-Pack. In the later update, we can consider to adding these feature into the sfm_elk since more factors are involved.
### X-Pack Trial
* **account management:** We need to keep track of the password of the elasticsearch user since the logstash need password to feed data to the elasticsearch. We also can use elasticsearch itself to load data instead of the logstash. We can think about it later.
* **license update**: Initially, the trial license will expire in one month. We need to do some work to allow users to update their own license.  For details, go [here](https://www.elastic.co/guide/en/x-pack/5.0/installing-license.html).

**Comment by Tanych** [comment]
## Test Guide
* 1. Requirements for Host 
    * set the docker host virtual memory to at least `262144`. To avoid the `virtual memory` error.

   * set the `ES_JAVA_OPTS` for 2g or larger in order to get a better performance, if you test machine has less memory than this, it might wait a litter longer time to start the elasticsearch. For setting details, https://www.elastic.co/guide/en/elasticsearch/reference/master/heap-size.html

* 2. Uncomment the elk containers on the `docker-compose.yml` file, pull the image.
* 3. Check whether the elasticsearch, kibana, logstash container running.
* 4. Build a twitter collection and collect some tweets.
* 5. Go to http://localhost:5601 to check the Twitter dashboard(it's the default page for kibana).

**Comment by Tanych** [comment]
### Initial Test
#### Machine Host
* Ubuntu 14.4
* Memory 16G
* Elastcisearch Heap size 2G
* Total Tweets: 516,599
#### Logging Warc 
* Index Total Tweets: about 120,000
#### Result
Elasticsearch change status to red.

![status_1](https://cloud.githubusercontent.com/assets/3956411/25280225/32b066e4-2677-11e7-9394-51836b53beb1.PNG)

#### Restart the Kibana and Increase heapsize to 4G, index error:

```
"indexed\":false,\"analyzed\":false,\"doc_values\":false}]", "timeFieldName": "@timestamp", "title": "logstash-*"}]}]]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.retryBecauseUnavailable(TransportReplicationAction.java:862) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.retryIfUnavailable(TransportReplicationAction.java:699) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.doRun(TransportReplicationAction.java:653) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$2.onTimeout(TransportReplicationAction.java:816) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:311) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:139) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:111) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:103) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.retry(TransportReplicationAction.java:802) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.retryBecauseUnavailable(TransportReplicationAction.java:862) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.retryIfUnavailable(TransportReplicationAction.java:699) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.doRun(TransportReplicationAction.java:653) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$2.onNewClusterState(TransportReplicationAction.java:805) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onNewClusterState(ClusterStateObserver.java:297) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.postAdded(ClusterStateObserver.java:208) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.cluster.service.ClusterService$1.run(ClusterService.java:364) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:544) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:238) [elasticsearch-5.3.0.jar:5.3.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:201) [elasticsearch-5.3.0.jar:5.3.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92-internal]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92-internal]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92-internal]

```
Elasticsearch tries to initial the kibana template and index at the start time. The elastcisearch will take 2 or 5 minutes to recover the large index. It occurs such error because the elasticsearch doesn't start fully. To get rid of this, the initial work should do only at the first time start.

### Next Round with 4G heapsize

**Comment by Tanych** [comment]
### Second Round with 4G heap size
Still not enough. Error with out of memory of java heap size.
![outofmem](https://cloud.githubusercontent.com/assets/3956411/25307295/749dac92-276c-11e7-887f-d3e14460e4c1.PNG)

### Third Round with 6G heap size 
All the 13087 Warc file has been loaded into the elastcisearch. Finally status:
* cluster health:
```
{
  "cluster_name": "sfm_prod",
  "status": "yellow",
  "timed_out": false,
  "number_of_nodes": 1,
  "number_of_data_nodes": 1,
  "active_primary_shards": 8395,
  "active_shards": 8395,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 8395,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 50
}
```
* index statues;
```
{
  "_shards": {
    "total": 16790,
    "successful": 8395,
    "failed": 0
  },
  "_all": {
    "primaries": {
      "docs": {
        "count": 290514,
        "deleted": 5602
      },
      "store": {
        "size_in_bytes": 479597760,
        "throttle_time_in_millis": 0
      },
      "indexing": {
        "index_total": 18645,
        "index_time_in_millis": 42578,
        "index_current": 0,
        "index_failed": 0,
        "delete_total": 0,
        "delete_time_in_millis": 0,
        "delete_current": 0,
        "noop_update_total": 0,
        "is_throttled": false,
        "throttle_time_in_millis": 0
      },
<--cut for breivty-->
```
### Fourth round turn on the monitoring 
Other optimal setting
* index performance parameters
```
# increse space for index 
# see https://www.elastic.co/guide/en/elasticsearch/reference/5.x/tune-for-indexing-speed.html#_indexing_buffer_size
indices.memory.index_buffer_size: 30%
# increase the index refresh interval
# see https://www.elastic.co/guide/en/elasticsearch/reference/5.x/tune-for-indexing-speed.html#_increase_the_refresh_interval
refresh_interval: 30s
```
* Disable swapping
`bootstrap.memory_lock =true`

* Ref: 
https://www.elastic.co/blog/performance-considerations-elasticsearch-indexing
https://www.elastic.co/guide/en/elasticsearch/reference/5.x/tune-for-indexing-speed.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-translog.html
https://sematext.com/blog/2013/07/08/elasticsearch-refresh-interval-vs-indexing-performance/

**Comment by Tanych** [comment]
@justinlittman the insensitive-case search for top-10-hashtag might have some problem, the 5.x dynamic mapping doesn't work well.  I have tried mapping `text` or `keyword`. It will make the field not aggregatable for visualization.

**Comment by justinlittman** [comment]
@Tanych here are my notes on our conversation:
1. Additional work is needed to be able to run multiple instances. This will involve creating links between elasticsearch, logstash, and kibana containers. Also, docs will need to be updated.
2. Need to figure out correct wording for 3 column of logging.quiet.
3. In various start.sh, remove wait loop and replace with larger appdeps wait.
4. Change startup process, so that:
    * Elasticsearch: ES starts. (It doesn't need to wait for Logstash or Kibana.)
    * Logstash: Waits for ES and then waits for ES to not be red. elk_loader then starts.
    * Kibana: Kibana waits for ES and then waits for ES to not be red. Kibana then starts.
    * Need to figure out were elk_config_loader fits into this.
    * Having links from Logstash/Kibana to Elasticsearch will make sure start order is correct.
5. Make memory configuration clearer in docs and docker-compose.yml files. Should the settings be same or different?
6. Add annotations to ulimits in docker-compose.yml.

In addition, I will be making edits to the docs and docker-compose.yml files.

**Comment by justinlittman** [comment]
Fixed by:
* https://github.com/gwu-libraries/sfm-ui/pull/790
* https://github.com/gwu-libraries/sfm-elk/pull/11
* https://github.com/gwu-libraries/sfm-docker/pull/18
