### ISSUE TITLE
Bad wording of harvest warning

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#772]
<img width="835" alt="2017-04-06_0725" src="https://cloud.githubusercontent.com/assets/588335/24752074/5bb1f578-1a9a-11e7-86a8-2a8f62af6633.png">

**Comment by lwrubel** [comment]
Look at twitter harvester message and make actual screen name appear in message instead of "screen_name".

**Comment by justinlittman** [comment]
Pull request is https://github.com/gwu-libraries/sfm-twitter-harvester/pull/37

(@rithvikmundra -- it's helpful to put a reference to the pull requests, especially when they're in another repo.)

**Comment by yonahbg** [comment]
This problem is now occurring for new seeds that don't work; it says "user screen_name" instead of the input name (which it used to do).

![screen_name warnings](https://cloud.githubusercontent.com/assets/23175249/25436497/692e27e0-2a61-11e7-9d5f-f814913b7444.JPG)
![more user screen_name examples](https://cloud.githubusercontent.com/assets/23175249/25436498/692e03d2-2a61-11e7-9ef4-ae646141e8df.JPG)
