### ISSUE TITLE
improve performance of collection_detail loading

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#804]
There is a lot happening on this page. @Tanych has identified some areas for improving this. It's especially evident in loading collections with a lot of seeds (e.g. Program on Extremism).

**Comment by Tanych** [comment]
@lwrubel  I have done some work on the PR https://github.com/gwu-libraries/sfm-ui/pull/806. 
Other work will double-check later with the performance.

**Comment by justinlittman** [comment]
Working with large collections such as the news outlets extremely slow. Fixing this should be a top priority.

**Comment by lwrubel** [comment]
refs #849 and ux-cleanup work

**Comment by Tanych** [comment]
@lwrubel @justinlittman 
as tested, the major cost would on getting the change log called by `diff_historical_object`. It usually takes about 80% percent of the page loading time which usually take near 2 seconds. It linearly increases by the seed size. The collection page only needs top-3 of the historical record. Need to rewrite some part of this code.

**Comment by Tanych** [comment]
@justinlittman 
### Profiling the Change log
The change log is one the major factor to slow down the collection detail page, let's take a deep look at how much time cost for the change log.
## Scenario
* One Collection 
* 5000 seeds, each seed only do the add.
* Total cost nearly `11s`.

## Profiling the diff_collection_and_seeds_history
![profile_collection_and_seed](https://user-images.githubusercontent.com/3956411/27872126-baba3086-6175-11e7-8351-ea3256c4f09f.png)

The major cost is on the **append seed history** record, let's go down the function.

## Profiling the diff_object_history
![profile_object_history](https://user-images.githubusercontent.com/3956411/27872182-e82d59da-6175-11e7-92c2-b8a5d550833e.png)
The major costs are on the `list(obj.history.all)` and `generate the diff object`. For check the obj history, not sure whether there is any way to speed up. For generate the diff object, let's go future.

## Profiling the diff_historical_object
![diff_historical](https://user-images.githubusercontent.com/3956411/27872264-3332fe08-6176-11e7-84a0-f22342265600.png)
The major cost is on `diff.user = changed_historical_object.history_user`, it takes over 90% percent of the time. To get the history user, we need to find another way to speed up.

**Comment by Tanych** [comment]
@justinlittman 
Currently, no better way to improve the performance on both the collection and seed change log. No matter what I do improve the merge function or using `reduce` to iterator the history record. It only improves 1-2s. When we try to iterator all the seeds history and collection history every one pair. The major cost is still there. Every time the history_user take so much time since the `history_user` was designed as a foreign key to the `User` model.  
The temporary relief solution could remove the seed change log on the collection page. The seed change log only shows the corresponding seed page.
