### ISSUE TITLE
Send apache logs to stdout

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#87]
Because it's the docker thing to do.

(Currently they log to `/var/log/apache2`.)

**Comment by dchud** [comment]
Are there docs on this you could point us to?

On Dec 17, 2015, at 7:40 AM, Justin Littman <notifications@github.com>
wrote:

Because it's the docker thing to do.

(Currently they log to /var/log/apache2.)

—
Reply to this email directly or view it on GitHub
<https://github.com/gwu-libraries/sfm-ui/issues/87>.

**Comment by justinlittman** [comment]
Inspired by https://medium.com/@kelseyhightower/12-fractured-apps-1080c73d481c#.pho5nr6mt.

Motivated by our experiences doing development on sfm-ui and driven to action by the fact that we had to remind ourselves in documentation that sfm-ui logging was going to the Apache logs and how to get to them.

From a docker perspective, this puts the logs in front of our faces and where they can be readily collected  (if we collect logs in the future).
