### ISSUE TITLE
When viewing full change log, 'Fields' values mostly render blank

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#952]
When viewing the change log on a collection page (at ui/collection/\<collection-number\> ), the `Fields` column is populated:

![image](https://user-images.githubusercontent.com/3451175/45638525-6ef39100-ba7b-11e8-8414-9dbd143fa44f.png)

However, when clicking on `View all {n} changes` ( ui/collection/\<collection-number\>/changes/, the resulting view has a `Fields` column that is mostly empty (there are a few exceptions):

![image](https://user-images.githubusercontent.com/3451175/45638563-8d598c80-ba7b-11e8-9318-924c2c7f6483.png)

**Comment by lwrubel** [comment]
iteritems() is not used in Python 3, which is why nothing is showing up from the historical objects. Instead, we should use items(). (See [PEP3106](https://www.python.org/dev/peps/pep-3106/))

The one other use of iteritems() in SFM is the README created with export and it will need to be updated as well.
